### ISSUE TITLE
How to publish anything "reactively" ?

### ISSUE THREAD

**Issue by wuxianliang** [dburles/meteor-capture-pubsub#1]
Dear @dburles 
Thank you for sharing knowledge on publish, I have use it for connecting Google API. Nowadays, I want to integrate OrienDB with Meteor. And I have a try on publish data from Neo4j to the client. It WORKS! But I still can not publish reactively. So is there a simple way to publish reactively?

I have tried reactivePublish, it does not work because it works with mongo.collection.

There are two kinds of reactivity. One is from database to meteor, the other is from server side to client side. I am working the first one now.

Thank you very much!

**Comment by dburles** [comment]
Thanks @wuxianliang. Yes it's possible, you will have to hook into these changes, and then you can use other parts of the publish API such as `this.changed()` and `this.removed()`. See: http://docs.meteor.com/#/full/publish_changed

Hope that helps!

Edit: Reading again it looks like you're unsure how to hook into changes happening within Neo4j, I can't really answer that and it is essentially very complex. I believe there are some guys working on Neo4j for Meteor https://github.com/kainolophobia/neo4j-livedata but I think the project has stalled.

**Comment by wuxianliang** [comment]
Thank you, I will have a try these days.
